/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as AreasDeCuidadoRouteImport } from './routes/areas-de-cuidado'
import { Route as TeleconsultaRouteImport } from './routes/teleconsulta'
import { Route as TrajetoriaRouteImport } from './routes/trajetoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeCuidadoRoute = AreasDeCuidadoRouteImport.update({
  id: '/areas-de-cuidado',
  path: '/areas-de-cuidado',
  getParentRoute: () => rootRouteImport,
} as any)
const TeleconsultaRoute = TeleconsultaRouteImport.update({
  id: '/teleconsulta',
  path: '/teleconsulta',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajetoriaRoute = TrajetoriaRouteImport.update({
  id: '/trajetoria',
  path: '/trajetoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/areas-de-cuidado': typeof AreasDeCuidadoRoute
  '/teleconsulta': typeof TeleconsultaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/areas-de-cuidado': typeof AreasDeCuidadoRoute
  '/teleconsulta': typeof TeleconsultaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/areas-de-cuidado': typeof AreasDeCuidadoRoute
  '/teleconsulta': typeof TeleconsultaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/agendamento' | '/areas-de-cuidado' | '/teleconsulta' | '/trajetoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/agendamento' | '/areas-de-cuidado' | '/teleconsulta' | '/trajetoria'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/areas-de-cuidado'
    | '/teleconsulta'
    | '/trajetoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AreasDeCuidadoRoute: typeof AreasDeCuidadoRoute
  TeleconsultaRoute: typeof TeleconsultaRoute
  TrajetoriaRoute: typeof TrajetoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-cuidado': {
      id: '/areas-de-cuidado'
      path: '/areas-de-cuidado'
      fullPath: '/areas-de-cuidado'
      preLoaderRoute: typeof AreasDeCuidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teleconsulta': {
      id: '/teleconsulta'
      path: '/teleconsulta'
      fullPath: '/teleconsulta'
      preLoaderRoute: typeof TeleconsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajetoria': {
      id: '/trajetoria'
      path: '/trajetoria'
      fullPath: '/trajetoria'
      preLoaderRoute: typeof TrajetoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AreasDeCuidadoRoute: AreasDeCuidadoRoute,
  TeleconsultaRoute: TeleconsultaRoute,
  TrajetoriaRoute: TrajetoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
